CREATE TABLE merchant_entity
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    company_name      VARCHAR(255)                            NOT NULL,
    inn               VARCHAR(255)                            NOT NULL,
    login             VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255)                            NOT NULL,
    merchant_status   VARCHAR(255)                            NOT NULL,
    first_account_id  UUID                                    NOT NULL,
    second_account_id UUID                                    NOT NULL,
    CONSTRAINT pk_merchant_entity PRIMARY KEY (id)
);

CREATE TABLE terminal_entity
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    merchant_id     BIGINT                                  NOT NULL,
    webhook_url     VARCHAR(255),
    terminal_status SMALLINT,
    CONSTRAINT pk_terminal_entity PRIMARY KEY (id)
);

ALTER TABLE merchant_entity
    ADD CONSTRAINT uc_merchant_entity_companyname UNIQUE (company_name);

ALTER TABLE merchant_entity
    ADD CONSTRAINT uc_merchant_entity_inn UNIQUE (inn);

ALTER TABLE merchant_entity
    ADD CONSTRAINT uc_merchant_entity_login UNIQUE (login);

ALTER TABLE terminal_entity
    ADD CONSTRAINT FK_TERMINAL_ENTITY_ON_MERCHANT FOREIGN KEY (merchant_id) REFERENCES merchant_entity (id);